/* I ran following commands while setting up SnowConvert AI and for the process of creating AdventureWorks database objects in SQL. 

Please note that most of the tables that were created on Snowflake side were not populated as the goal was to practice ETL Migration using Airflow. So, the actual data wasn't copied over. Rather, just the table structures were made available. 

CREATE TABLE commands below were run from here because SnowConvert AI was not allowing to do so from UI. The app was still in Preview mode as of '19-Nov-2025'. So, for some objects, I had to manually make changes in the script generated by SnowConvert AI and run them in Snowsight.

In addition to this, after having created all the tables within all the schemas of AdventureWorks database, I have taken backup of the DDL commands, which can be reused every time I switch snowflake trial account(To create the database, schemas within the database and tables within the schemas again). This is stored in a different file.

*/

ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'AWS_US';

USE DATABASE ADVENTUREWORKS;

select * from dbo.errorlog;

select * from person.person;

select * from humanresources.employeedepartmenthistory;

CREATE OR REPLACE TABLE Production.ScrapReason (
    ScrapReasonID SMALLINT NOT NULL,
    Name VARCHAR NOT NULL,
    ModifiedDate TIMESTAMP_NTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ)
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 20,  "patch": "10.0" }, "attributes": {  "component": "transact",  "convertedOn": "11/13/2025",  "domain": "gyknife",  "migrationid": "aHyaAYUPyH+Bfvdm7wR0Mw==" }}'
;

CREATE OR REPLACE TABLE Production.ProductCategory (
    ProductCategoryID INT NOT NULL,
    Name VARCHAR NOT NULL,
    rowguid VARCHAR NOT NULL DEFAULT (UUID_STRING()),
    ModifiedDate TIMESTAMP_NTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ)
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 20,  "patch": "10.0" }, "attributes": {  "component": "transact",  "convertedOn": "11/13/2025",  "domain": "gyknife",  "migrationid": "aHyaAYUPyH+Bfvdm7wR0Mw==" }}'
;

CREATE OR REPLACE TABLE Production.Product (
    ProductID INT NOT NULL,
    Name VARCHAR NOT NULL,
    ProductNumber NVARCHAR(50) NOT NULL,
    MakeFlag BOOLEAN NOT NULL DEFAULT ((true)),
    FinishedGoodsFlag BOOLEAN NOT NULL DEFAULT ((true)),
    Color NVARCHAR(30) NULL,
    SafetyStockLevel SMALLINT NOT NULL,
    ReorderPoint SMALLINT NOT NULL,
    StandardCost NUMBER(38, 4) NOT NULL,
    ListPrice NUMBER(38, 4) NOT NULL,
    Size NVARCHAR(10) NULL,
    SizeUnitMeasureCode NCHAR(6) NULL,
    WeightUnitMeasureCode NCHAR(6) NULL,
    Weight DECIMAL(8, 2) NULL,
    DaysToManufacture INT NOT NULL,
    ProductLine NCHAR(4) NULL,
    Class NCHAR(4) NULL,
    Style NCHAR(4) NULL,
    ProductSubcategoryID INT NULL,
    ProductModelID INT NULL,
    SellStartDate TIMESTAMP_NTZ NOT NULL,
    SellEndDate TIMESTAMP_NTZ NULL,
    DiscontinuedDate TIMESTAMP_NTZ NULL,
    rowguid VARCHAR NOT NULL DEFAULT (UUID_STRING()),
    ModifiedDate TIMESTAMP_NTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ)
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 20,  "patch": "10.0" }, "attributes": {  "component": "transact",  "convertedOn": "11/13/2025",  "domain": "gyknife",  "migrationid": "aHyaAYUPyH+Bfvdm7wR0Mw==" }}'
;

CREATE OR REPLACE TABLE Production.ScrapReason (
    ScrapReasonID SMALLINT NOT NULL,
    Name VARCHAR NOT NULL,
    ModifiedDate TIMESTAMP_NTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ)
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 20,  "patch": "10.0" }, "attributes": {  "component": "transact",  "convertedOn": "11/13/2025",  "domain": "gyknife",  "migrationid": "aHyaAYUPyH+Bfvdm7wR0Mw==" }}'
;

CREATE OR REPLACE TABLE Production.ProductCategory (
    ProductCategoryID INT NOT NULL,
    Name VARCHAR NOT NULL,
    rowguid VARCHAR NOT NULL DEFAULT (UUID_STRING()),
    ModifiedDate TIMESTAMP_NTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ)
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 20,  "patch": "10.0" }, "attributes": {  "component": "transact",  "convertedOn": "11/13/2025",  "domain": "gyknife",  "migrationid": "aHyaAYUPyH+Bfvdm7wR0Mw==" }}'
;

CREATE OR REPLACE TABLE Production.ProductProductPhoto (
    ProductID INT NOT NULL,
    ProductPhotoID INT NOT NULL,
       "Primary" SMALLINT NOT NULL DEFAULT 1,
    ModifiedDate TIMESTAMP_NTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ)
   )
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 20,  "patch": "10.0" }, "attributes": {  "component": "transact",  "convertedOn": "11/13/2025",  "domain": "gyknife",  "migrationid": "aHyaAYUPyH+Bfvdm7wR0Mw==" }}'
;

CREATE OR REPLACE TABLE Production.ProductReview (
    ProductReviewID INT NOT NULL,
    ProductID INT NOT NULL,
    ReviewerName VARCHAR NOT NULL,
    ReviewDate TIMESTAMP_NTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ),
    EmailAddress NVARCHAR(100) NOT NULL,
    Rating INT NOT NULL,
    Comments NVARCHAR(7700) NULL,
    ModifiedDate TIMESTAMP_NTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ)
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 20,  "patch": "10.0" }, "attributes": {  "component": "transact",  "convertedOn": "11/13/2025",  "domain": "gyknife",  "migrationid": "aHyaAYUPyH+Bfvdm7wR0Mw==" }}'
;

CREATE OR REPLACE TABLE Production.ProductSubcategory (
    ProductSubcategoryID INT NOT NULL,
    ProductCategoryID INT NOT NULL,
    Name VARCHAR NOT NULL,
    rowguid VARCHAR NOT NULL DEFAULT (UUID_STRING()),
    ModifiedDate TIMESTAMP_NTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ)
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 20,  "patch": "10.0" }, "attributes": {  "component": "transact",  "convertedOn": "11/13/2025",  "domain": "gyknife",  "migrationid": "aHyaAYUPyH+Bfvdm7wR0Mw==" }}'
;

CREATE OR REPLACE TABLE Production.Culture (
    CultureID NCHAR(12) NOT NULL,
    Name VARCHAR NOT NULL,
    ModifiedDate TIMESTAMP_NTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ)
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 20,  "patch": "10.0" }, "attributes": {  "component": "transact",  "convertedOn": "11/13/2025",  "domain": "gyknife",  "migrationid": "aHyaAYUPyH+Bfvdm7wR0Mw==" }}'
;

CREATE OR REPLACE TABLE Production.Location (
    LocationID SMALLINT NOT NULL,
    Name VARCHAR NOT NULL,
    CostRate NUMBER(38, 4) NOT NULL DEFAULT 0.0,
    Availability DECIMAL(8, 2) NOT NULL DEFAULT ((0.00)),
    ModifiedDate TIMESTAMP_NTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ)
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 20,  "patch": "10.0" }, "attributes": {  "component": "transact",  "convertedOn": "11/13/2025",  "domain": "gyknife",  "migrationid": "aHyaAYUPyH+Bfvdm7wR0Mw==" }}'
;

CREATE OR REPLACE TABLE Production.UnitMeasure (
    UnitMeasureCode NCHAR(6) NOT NULL,
    Name VARCHAR NOT NULL,
    ModifiedDate TIMESTAMP_NTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ)
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 20,  "patch": "10.0" }, "attributes": {  "component": "transact",  "convertedOn": "11/13/2025",  "domain": "gyknife",  "migrationid": "aHyaAYUPyH+Bfvdm7wR0Mw==" }}'
;

CREATE OR REPLACE TABLE Purchasing.ShipMethod (
    ShipMethodID INT NOT NULL,
    Name VARCHAR NOT NULL,
    ShipBase NUMBER(38, 4) NOT NULL DEFAULT ((0.00)),
    ShipRate NUMBER(38, 4) NOT NULL DEFAULT ((0.00)),
    rowguid VARCHAR NOT NULL DEFAULT (UUID_STRING()),
    ModifiedDate TIMESTAMP_NTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ)
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 20,  "patch": "10.0" }, "attributes": {  "component": "transact",  "convertedOn": "11/13/2025",  "domain": "gyknife",  "migrationid": "aHyaAYUPyH+Bfvdm7wR0Mw==" }}'
;

CREATE OR REPLACE TABLE Purchasing.Vendor (
    BusinessEntityID INT NOT NULL,
    AccountNumber VARCHAR NOT NULL,
    Name VARCHAR NOT NULL,
    CreditRating TINYINT NOT NULL,
    PreferredVendorStatus BOOLEAN NOT NULL DEFAULT TRUE,
    ActiveFlag BOOLEAN NOT NULL DEFAULT TRUE,
    PurchasingWebServiceURL NVARCHAR NULL,
    ModifiedDate TIMESTAMP_NTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ)
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 20,  "patch": "10.0" }, "attributes": {  "component": "transact",  "convertedOn": "11/13/2025",  "domain": "gyknife",  "migrationid": "aHyaAYUPyH+Bfvdm7wR0Mw==" }}'
;

CREATE OR REPLACE TABLE Sales.Currency (
    CurrencyCode NCHAR NOT NULL,
    Name VARCHAR NOT NULL,
    ModifiedDate TIMESTAMP_NTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ)
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 20,  "patch": "10.0" }, "attributes": {  "component": "transact",  "convertedOn": "11/13/2025",  "domain": "gyknife",  "migrationid": "aHyaAYUPyH+Bfvdm7wR0Mw==" }}'
;

CREATE OR REPLACE TABLE Sales.SalesOrderHeader (
    SalesOrderID INT NOT NULL,
    RevisionNumber TINYINT NOT NULL DEFAULT 0,
    OrderDate TIMESTAMP_NTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ),
    DueDate TIMESTAMP_NTZ NOT NULL,
    ShipDate TIMESTAMP_NTZ NULL,
    Status TINYINT NOT NULL DEFAULT 1,
    OnlineOrderFlag BOOLEAN NOT NULL DEFAULT TRUE,
    SalesOrderNumber VARCHAR(50) NOT NULL,
    PurchaseOrderNumber VARCHAR NULL,
    AccountNumber VARCHAR NULL,
    CustomerID INT NOT NULL,
    SalesPersonID INT NULL,
    TerritoryID INT NULL,
    BillToAddressID INT NOT NULL,
    ShipToAddressID INT NOT NULL,
    ShipMethodID INT NOT NULL,
    CreditCardID INT NULL,
    CreditCardApprovalCode VARCHAR(15) NULL,
    CurrencyRateID INT NULL,
    SubTotal NUMBER(38, 4) NOT NULL DEFAULT ((0.00)),
    TaxAmt NUMBER(38, 4) NOT NULL DEFAULT ((0.00)),
    Freight NUMBER(38, 4) NOT NULL DEFAULT ((0.00)),
    TotalDue NUMBER(38, 4) NOT NULL,
    Comment NVARCHAR(256) NULL,
    rowguid VARCHAR NOT NULL DEFAULT (UUID_STRING()),
    ModifiedDate TIMESTAMP_NTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ)
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 20,  "patch": "10.0" }, "attributes": {  "component": "transact",  "convertedOn": "11/13/2025",  "domain": "gyknife",  "migrationid": "aHyaAYUPyH+Bfvdm7wR0Mw==" }}'
;

CREATE OR REPLACE TABLE Sales.SalesReason (
    SalesReasonID INT NOT NULL,
    Name VARCHAR NOT NULL,
    ReasonType VARCHAR NOT NULL,
    ModifiedDate TIMESTAMP_NTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ)
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 20,  "patch": "10.0" }, "attributes": {  "component": "transact",  "convertedOn": "11/13/2025",  "domain": "gyknife",  "migrationid": "aHyaAYUPyH+Bfvdm7wR0Mw==" }}'
;

CREATE OR REPLACE TABLE Sales.SalesTaxRate (
    SalesTaxRateID INT NOT NULL,
    StateProvinceID INT NOT NULL,
    TaxType TINYINT NOT NULL,
    TaxRate NUMBER(38, 4) NOT NULL DEFAULT 0.0,
    Name VARCHAR NOT NULL,
    rowguid VARCHAR NOT NULL DEFAULT (UUID_STRING()),
    ModifiedDate TIMESTAMP_NTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ)
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 20,  "patch": "10.0" }, "attributes": {  "component": "transact",  "convertedOn": "11/13/2025",  "domain": "gyknife",  "migrationid": "aHyaAYUPyH+Bfvdm7wR0Mw==" }}'
;

CREATE OR REPLACE TABLE Sales.SalesTerritory (
    TerritoryID INT NOT NULL,
    Name VARCHAR NOT NULL,
    CountryRegionCode NVARCHAR(6) NOT NULL,
    "Group" NVARCHAR(100) NOT NULL,
    SalesYTD NUMBER(38, 4) NOT NULL DEFAULT 0.0,
    SalesLastYear NUMBER(38, 4) NOT NULL DEFAULT 0.0,
    CostYTD NUMBER(38, 4) NOT NULL DEFAULT 0.0,
    CostLastYear NUMBER(38, 4) NOT NULL DEFAULT 0.0,
    rowguid VARCHAR NOT NULL DEFAULT (UUID_STRING()),
    ModifiedDate TIMESTAMP_NTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ)
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 20,  "patch": "10.0" }, "attributes": {  "component": "transact",  "convertedOn": "11/13/2025",  "domain": "gyknife",  "migrationid": "aHyaAYUPyH+Bfvdm7wR0Mw==" }}'
;

select top 10 * from information_schema.tables;

select get_ddl('DATABASE', 'AdventureWorks', TRUE);

select table_schema, COUNT(*) Table_Count from information_schema.tables
where table_catalog =  'ADVENTUREWORKS' and table_schema <> 'INFORMATION_SCHEMA'
group by table_schema
order by 1;

select * from information_schema.tables
where table_catalog =  'ADVENTUREWORKS' and table_schema = 'PERSON'
order by table_name;

CREATE OR REPLACE TABLE dbo.DatabaseLog (
    DatabaseLogID INT NOT NULL,
    PostTime TIMESTAMP_NTZ(3) NOT NULL,
    DatabaseUser VARCHAR(128) NOT NULL,
    Event VARCHAR(128) NOT NULL,
    "Schema" VARCHAR(128) NULL,
    Object VARCHAR(128) NULL,
    TSQL NVARCHAR NOT NULL,
    XmlEvent VARIANT
NOT NULL
   )
   COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 20,  "patch": "10.0" }, "attributes": {  "component": "transact",  "convertedOn": "11/13/2025",  "domain": "gyknife",  "migrationid": "aHyaAYUPyH+Bfvdm7wR0Mw==" }}'
   ;

CREATE OR REPLACE TABLE HumanResources.JobCandidate (
    JobCandidateID INT NOT NULL,
    BusinessEntityID INT NULL,
    Resume VARIANT
NULL,
    ModifiedDate TIMESTAMP_NTZ(3) NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ(3))
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 20,  "patch": "10.0" }, "attributes": {  "component": "transact",  "convertedOn": "11/13/2025",  "domain": "gyknife",  "migrationid": "aHyaAYUPyH+Bfvdm7wR0Mw==" }}'
;