USE DATABASE SNOWFLAKE_PRACTICE_DEV;

USE SCHEMA RAW;

CREATE OR REPLACE PROCEDURE SP_CHECK_FOR_QUERIES()
RETURNS VARCHAR NOT NULL
LANGUAGE SQL
EXECUTE AS CALLER
AS
DECLARE
    row_count INTEGER DEFAULT 0;
BEGIN
    SELECT COUNT(*) INTO :row_count from marked_running_queries where MARKED_FLAG = 'Y';
    IF (row_count = 0) THEN
        CALL SYSTEM$SET_RETURN_VALUE('SKIP');
    ELSE
        CALL SYSTEM$SET_RETURN_VALUE('RUN_KILL');
        RETURN 'Queries found. Triggering kill task.';
    END IF;
END;
