USE DATABASE SNOWFLAKE_PRACTICE_DEV;

USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT FF_CSV_ORDERS
TYPE = CSV
FIELD_DELIMITER = ','
PARSE_HEADER = TRUE
SKIP_BLANK_LINES = TRUE
ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
;

